site/pages/v4/accessibility/index-en.hbs, site/pages/v4/accessibility/requirements/_template-en.hbs, site/pages/v4/accessibility/requirements/forms-en.hbs, site/pages/v4/accessibility/requirements/headings-en.hbs, site/pages/v4/accessibility/requirements/images-en.hbs, site/pages/v4/accessibility/requirements/language-en.hbs, site/pages/v4/accessibility/requirements/links-en.hbs, site/pages/v4/accessibility/requirements/page-titles-en.hbs, site/pages/v4/accessibility/requirements/quotations-en.hbs, site/pages/v4/accessibility/requirements/related-links-en.hbs, site/pages/v4/accessibility/requirements/tables-en.hbs, site/pages/v4/accessibility/requirements/text-en.hbs, site/pages/v4/accessibility/requirements/ui-controls-en.hbs, site/pages/v4/usability/tables-en.hbs
Though this PR doesn't address all issues in https://github.com/wet-boew/wet-boew-styleguide/issues/118 or https://github.com/wet-boew/wet-boew-styleguide/issues/137, it provides a great skeleton to start building and porting over the bulk of the [optimal content tools](http://wet-boew.github.io/wet-boew-legacy/v3.1/demos/tableparser/validator-htmltable.html) **and** [optimal content examples](http://wet-boew.github.io/wet-boew-legacy/v3.1/demos/opt-cont/index-en.html) (as per issue https://github.com/wet-boew/wet-boew-styleguide/issues/118). Thanks.
=> Updates accessibility guide. Related to #118 and #137.

site/pages/v4/design/forms-en.hbs
=> Forms: Changed the location of the hidden label to fix a border-radius issue with input-group

site/pages/v4/design/icons-en.hbs
=> Removed Dropdown toggle example #7193 

site/pages/v4/writing/dvlpmnt-en.hbs, site/pages/v4/writing/strctr-en.hbs
Accidently put the files in the root of master instead of the writing/ folder.
=> Correct bilingual 'writing' pages in 'writing' folder

site/data/i18n/fr.json
Resolves build failures that started in #285.
CC @cfarquharson @MaximMartel @LaurentGoderre @nschonni @shawnthompson
=> Breadcrumbs: Added French i18n file.

site/pages/v4/writing/prncpls-en.hbs, site/pages/v4/writing/prncpls-fr.hbs
=> Removed decorative images from page

site/pages/v4/design/css/gridify.scss
Local solution until there is a WET supported version
=> Uploaded custom CSS for filter function

site/pages/v4/index-en.hbs, site/pages/v4/index-fr.hbs
Newest bilingual content uploaded.
=> Files have been updated and made bilingual

site/pages/v4/design/forms-en.hbs, site/pages/v4/design/forms-fr.hbs
Related to [PR 7771](https://github.com/wet-boew/wet-boew/pull/7771)
=> Update forms style guide with new class

site/pages/v4/design/jumbotron-en.hbs, site/pages/v4/design/jumbotron-fr.hbs, site/pages/v4/design/pills-en.hbs, site/pages/v4/design/pills-fr.hbs, site/pages/v4/design/progressmeter-en.hbs, site/pages/v4/design/progressmeter-fr.hbs, site/pages/v4/design/whitespace-en.hbs, site/pages/v4/design/whitespace-fr.hbs
Updated the English content and created French content for Jumbotron, Pills, Progress meter.  Added new .wb.elps effect to documentation
=> Updated content on a few missing pages

site/pages/v4/design/forms-en.hbs, site/pages/v4/design/forms-fr.hbs
Please merge for [PR 7771](https://github.com/wet-boew/wet-boew/pull/7771)
=> Fixes the Fieldset Border Example

site/pages/v4/accessibility/guide-en.hbs
Corrects one of the three broken links in #118.
=> Fix link to the table validator.

site/pages/v4/design/forms-en.hbs, site/pages/v4/design/forms-fr.hbs
Related to [PR #7771](https://github.com/wet-boew/wet-boew/pull/7771)
=> Fix Forms design page

site/pages/v4/design/tables-en.hbs, site/pages/v4/design/tables-fr.hbs
=> Error in table code example

v4/index-en.html, v4/index-fr.html
=> Fix meta redirect

_config.yml, _layouts/default-theme-wet-boew-fr.html, accessibility/applicability-fr.md, accessibility/considerations-fr.md, accessibility/examples-fr.md, accessibility/examples-images-textdesc-fr.md, accessibility/guide-fr.md, accessibility/index-fr.md, accessibility/introduction-fr.md, accessibility/requirements/forms-fr.md, accessibility/requirements/headings-fr.md, accessibility/requirements/images-fr.md, accessibility/requirements/language-fr.md, accessibility/requirements/links-fr.md, accessibility/requirements/page-titles-fr.md, accessibility/requirements/quotations-fr.md, accessibility/requirements/related-links-fr.md, accessibility/requirements/tables-fr.md, accessibility/requirements/text-fr.md, accessibility/requirements/ui-controls-fr.md, index-en.md, index-fr.md
Addresses #369
Also following main wet-boew repo model add the French pages, but untranslated.
=> Provide Access To Accessibility Guide

404.html
For https://github.com/wet-boew/wet-boew/issues/8632
=> Fix Broken URLs

404.html
=> Fix Home Page Link

index-en.md, index-fr.md
=> Fix Broken Links

design/secmenu-en.md, design/secmenu-fr.md, index-en.md, index-fr.md
=> Adding secondary menu documentation

_includes/header-theme-wet-boew-en.html, _includes/header-theme-wet-boew-fr.html
Minor Bug with Language Switch
=> Minor Bug with Language Switch
